# Generated by Django 4.2.1 on 2024-04-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Is_admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Is_student',
            new_name='is_student',
        ),
    ]
