# Generated by Django 4.2.1 on 2024-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addopp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('eligibility', models.CharField(max_length=40)),
                ('skills', models.TextField()),
                ('min_stipend', models.PositiveIntegerField()),
                ('max_stipend', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('venue', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
            ],
        ),
    ]
